
# Loads default set of integrations. Do not remove.
default_config:

virtual:
  yaml_config: true
sensor: !include virtual_sensors.yaml
binary_sensor: !include virtual_binary_sensors.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
